main/main.c

Code from https://github.com/espressif/esp-idf/blob/master/examples/system/base_mac_address/main/base_mac_address_example_main.c to print out the WiFi MAC address (e.g. if using a network that requires pre-registration of devices).
(Take 2, clean and shiney, I hope! Sorry for the hassle.)

print the MAC address (e.g. for networks needing registration)

---

main/main.c

In 086dfc0fd22d ("main: trigger WAKEUP_END shortly after VAD_END"), we reduced the time between VAD_END and WAKEUP_END from 900ms to 100ms, and noted that setting it to 0 caused very weird behaviour. In further testing, we learned that setting it to 1 does not result in that same weird behaviour, so let's set it to 1 and shave of another 99ms of the response time.

main: trigger WAKE_END right after VAD_END

---

main/Kconfig.projbuild
main/main.c

When user server mode speech rec we increase (or allow the user to specify) the ADF record buffer due to potential internet latency and other timing issues.
This is a non-factor with local multinet command recognition so it's probably best to use the default values to avoid any potential edge cases.

Use default record ringbuffer values when using multinet

---

.gitignore

.DS_Store is a macOS file that can get added to repos if devs are not paying attention and .vscode is for the local Visual Studio Code settings.

ignore .DS_Store and .vscode for easier coordination with other dev PRs

---

speech_commands/generate_commands.py

While trying multinet today, the following error kept appearing:
W (79508) AFE_SR: ERROR! rb_out slow!!!
After some testing, it appears a command with 62 characters was causing this. We therefore believe the ESP_MN_MAX_PHRASE_LEN of 63 might include the command ID and the space.
Let's play safe, and filter out commands longer than 59 commands, so that with an ID between 100-400, we will not exceed the 63 characters.

speech_commands: include command ID when checking length

---

Dockerfile

Setting DEBIAN_FRONTEND=noninteractive via ENV is discouraged as it will persist in the final docker container when it is run. Using ARG here only exports this variable for the build steps.

Updated Dockerfile ENV to ARG

---

main/Kconfig.projbuild
main/main.c
main/shared.h
main/timer.c
main/timer.h

Add timer to force end stream

---

main/Kconfig.projbuild
main/main.c

This should allow people experiencing problems with the wake word to experiment with different accuracy.
Related to #111.
As this is something that should only be changed if instructed by us, move it in an "Advanced settings" submenu.

Kconfig: expose wake modes

---

main/Kconfig.projbuild
main/main.c

Use a hidden int with default based on the selected choice. This mimics the gain_value enum in es7210.h. This is cleaner than using ifdef.

Kconfig: add option for microphone gain

---

main/CMakeLists.txt

CMake: fail when HOMEASSISTANT_HOST contains URL scheme

---

main/endpoint/openhab.c

While working on dynamic config I found that we're not enabling HTTP Basic Authentication for openHAB. Strangely enough our openHAB test instance responds with HTTP 200 even without authentication, which explains why we never noticed this.

openhab: enable HTTP Basic Authentication

---

README.md

Remove content that is duplicated on heywillow.io. This way we won't have to maintain the same content in multiple locations, and the link to the documentation site is visibile without having to scroll down to the bottom of the page.

README.md: further cleanup

---

main/audio.c

Continuing to display "Say Command..." after speech has ended and the command has been sent to the command endpoint is poor and confusing UI. Print "Thinking..." after speech has ended while we're waiting for response.
Fixes #247

Print "Thinking..." on the display after speech while command is sent

---

Dockerfile
utils.sh

We currently point to the willow branch of our ESP-ADF fork. As long as we don't update that branch, this is fine, but once this branch gets updated, rebuilding Willow would result in a different binary, even when building a tag. This makes bisecting near impossible.
Use a commit hash instead of a branch name to avoid above problems.

treewide: use commit hash for ESP-ADF

---

Dockerfile
utils.sh

We currently point to the willow branch of our ESP-ADF fork. As long as we don't update that branch, this is fine, but once this branch gets updated, rebuilding Willow would result in a different binary, even when building a tag. This makes bisecting near impossible.
Use a commit hash instead of a branch name to avoid above problems.
(cherry picked from commit 2d0b90a8d625c07ab24e147cf6711cdccdbfb700)

backport: treewide: use commit hash for ESP-ADF

---

main/audio.c
main/ui.c

We previously disabled LVGL text scrolling to test if this would fix the display locking up, but we kept experiencing the lockups. We believe commit c8561a1076be ("sdkconfig: enable LCD_RGB_ISR_IRAM_SAFE") finally fixed the problem.
We do not want to risk this causing problems in the 0.1.0 release again, but now that we've branched release/v0.1, let's enable text scrolling again in main.
This reverts commit 5b46dbd7da9cff4945b6e93a6b134e709b06ce45.

Revert "treewide: disable text LVGL text scrolling"

---

main/audio.c
main/endpoint/hass.c
main/endpoint/openhab.c
main/endpoint/rest.c

Across our various command endpoints there is currently a lot of inconsistency in terms of user experience:
1) Some status lines still use red/green to communicate feedback. These are very low-contrast against our current purple background.
2) REST doesn't support TTS responses.
3) OpenHAB doesn't support TTS responses.
4) There is inconsistent language all over the place for generic responses - sometimes saying/display "Error!", other times "Error", etc.
5) REST and OpenHAB endpoints don't display the Response: text on LVGL line 4
This PR addresses these issues to bring a more consistent user experience across all supported command endpoints.

Standardize user experience across across all supported command endpoints.

---

.github/workflows/build-willow.yml
.github/workflows/meta.yml
main/audio.c
main/endpoint/hass.c
main/endpoint/openhab.c
main/endpoint/rest.c

And some CI changes required to make sure we build using the right container.

Backport endpoint consistency and CI changes to v0.1

---

Dockerfile
main/audio.c
main/audio.h
main/log.c
main/was.c
main/was.h

This PR implements handling of multiple Willow devices waking at the same time. With WAS support, only the Willow device with the highest wake word volume will send a command to the endpoint. Without WAS support, Willow will function like before.
It is possible to trigger VAD START before the wake_result is received from WAS, which will cause Willow devices who have lost the wake race to start streaming to WIS already. This should be improved, but will require some refactoring. For now, this should be good enough to demonstrate the feature, but the feature should be considered experimental.

Initial multiwake support

---

Dockerfile
main/audio.c

Espressif implemented passing wake volume to audio_recorder. Bump ESP-ADF to git HEAD and get wake volume using the new implementation.

treewide: bump ESP-ADF git HEAD

---

.github/workflows/build-container.yml
.github/workflows/meta.yml

When a commit doesn't trigger a container build, we build Willow in the container tagged main. If in a previous commit in the current branch or PR we made changes that actually require a container rebuild, CI can fail, as one of the Espressif frameworks could be out of date.
Fix this by moving the metadata extraction out of the build-container workflow into the meta workflow and use its outputs an inputs for the build workflows.

CI: build from correct container image tag

---

main/endpoint/hass.c

The fix for the potential leak can cause a null pointer deref crash.
This reverts commit de1e99f07a1b15f73227305149c39a98cd4598c0.

Revert "hass: fix potential memory leak"

---

main/ota.c

When an OTA partition is marked as bad due to it crashing, we currently abort OTA when we're trying to flash an OTA with the same version string. During development, we often build with the same version string used before, while the image contains different code. If this version string was marked invalid, we currently abort OTA and need to manually erase OTA data or create a new git commit to be able to flash our new image. This slows down development a bit.
As we fallback to the other OTA partition anyway, this extra check doesn't add much value, so simply drop it.

ota: drop invalid partition check

---

Dockerfile
dependencies.lock
main/idf_component.yml
main/slvgl.c
main/system.c
main/system.h

The pre-production units of the ESP32-S3-Box-3 uses a different touch
controller than the final model. Detect the model to make sure the touch
controller works on both versions.

Support the GT911 touch controller in the ESP32-S3-Box-3 final version

---

Dockerfile

The willow-main-2023110700 tag in our ESP-ADF fork contains some accidental changes to the git submodules.

Dockerfile: bump ESP-ADF to revert accidental changes

---

main/audio.c

In commit 349a8e47ebe7 ("treewide: define display timeout in seconds"), we changed reset_timer to convert the timeout to microseconds inside the function, but we forgot to change the reset_timer call for the session timer. As a result, the session timer was waiting for millions of seconds rather than just the number of seconds in the config.
Fixes: 349a8e47ebe7 ("treewide: define display timeout in seconds")

Fix session timer

---

main/audio.c
main/config.c

To have more flexibility with the new Coqui TTS backend, we're going to
construct the TTS URL in WAS before sending it to Willow.
We will support both the old and the new way for a while, both in Willow
and WAS, so that old Willow versions will work with new WAS versions,
and new Willow version will work with old WAS versions.

WIS TTS URL v2 support

---

main/audio.c
main/config.c
main/endpoint/hass.c
main/endpoint/rest.c
main/net/ethernet.c
main/network.c
main/system.c
main/ui.c
main/was.c

A bunch of UI changes mostly to avoid inconsistencies in text alignment.

UI improvements

---

main/main.c

We're assigning the return value of several functions to the variable ret, but when there's an error we print the name of err. As app_main doesn't return anything, drop the ret variable completely and use err everywhere.
Fixes: 36ee1f70bf1d ("main: read Wi-Fi credentials from NVS")
Fixes: ae4314713b8b ("main: get WAS URL from NVS")

main: fix error printing in app_main

---

main/audio.c

And increase the HTTP timeout after initial connect to 10s to accommodate users trying WIS on a slow GPU or CPU within reason.

Improve HTTP stream timeout error handling

---

main/was.c

With WAS Command Endpoint enabled, if a command endpoint takes long to respond, the display timer might expire before the response arrives. Reset the display timer when a response arrives.
Fixes #349.

was: reset display timer on WAS command endpoint result

---

Dockerfile
main/audio.c

This requires an ESP-ADF bump.
Closes: #125
Closes: #354

audio: only install I2S driver once

---

CMakeLists.txt
utils.sh

We haven't supported MultiNet in any of the Willow or WAS releases. Let's make it opt-in, rather than disabling it in CI builds. This will solve the missing generated_cmd_multinet.h file for people trying to build manually.
It is still possible to enable MultiNet when building manually by setting the MULTINET environment variable, but we will not provide support for any issues related to it. Issues will be closed without resolution.
Closes: #382

build: make MultiNet support opt-in

---

main/CMakeLists.txt
main/i2c.c
main/i2c.h
main/slvgl.c
main/system.c
main/system.h

And use it to probe for the I2C addresses of touch controllers used in
the ESP32-S3-Box variants supported by Willow. This is in preparation of
switching back to upstream ESP-ADF instead of our fork.
The i2c_bus_probe_addr function in ESP-ADF's i2c_bus driver rejects
addresses that use more than 7 bits, but does not set bit 8 to indicate
that we want to write from master to slave.

Implement i2c_probe function

---

Dockerfile
main/audio.c
main/input.c
main/shared.h
utils.sh

We need to add a fallback value for ES7210_MIC_SELECT, which is not defined in the board_def.h file for the ESP32-S3-Box-Lite. Commit espressif/esp-adf@ebb804bab9beb3e9ef6d1f3a1923aca2b94ae0b7 changed this to (ES7210_INPUT_MIC1 | ES7210_INPUT_MIC2 | ES7210_INPUT_MIC3) for the Box and the Box-3, and added a fallback value in es7210.c. Looking at espressif/esp-adf#1241, it appears MIC3 is used on Box and Box-3 for AEC. Looking at the schematics, the Box-Lite does not have MIC3 connected, so espressif/esp-adf@ebb804bab9beb3e9ef6d1f3a1923aca2b94ae0b7 corrected the situation correctly. If I understand things correctly, this means AEC was never functional in Willow, and this commit could potentially fix #342, and also avoid Willow from capturing TTS audio responses, on the Box and Box-3. …

build: bump to upstream ESP-ADF v2.7

---

.github/workflows/meta.yml

When we're pushing multiple commits, the changed-files actions only looks at the last commit. This can result in building Willow source code that requires a new build container without a new build container being built. Enable since_last_remote_commit in the changed-files actions to hopefully fix this. Unfortunately, since Github actions only looks at files in the main branch, we cannot test this before merging it into the main branch.

CI: detect changed files since last remote commit

---

utils.sh

This is the last version of esp-sr v1.
Torture test results: 1000/1000.

build: bump esp-sr to 1.9.5

---

.github/workflows/meta.yml
Dockerfile

If we don't trigger workflow on push, we will not build and push a new container image when a PR is merged. Because of this, the container image with the main tag is currently based on ESP-IDF v5.1, while we already have code in the main branch that requires ESP-IDF v5.2.
Trigger workflow on push again, but only for the main and release branches.
Also add an empty newline to Dockerfile to make sure we trigger container build and push, so that the container image with the main tag will be based on ESP-IDF v5.2.
Fixes: 390533f1c51a ("CI: don't trigger workflow on push")

CI: trigger workflow on push again

---

main/network.c

The ev_id value on its own is pretty useless without ev_base, as the event handler is register for both IP_EVENT and WIFI_EVENT.
Before:
I (18:32:27.019) WILLOW/NETWORK: unhandled network event ev_id='4'
After:
I (18:36:19.211) WILLOW/NETWORK: unhandled network event ev_base='WIFI_EVENT' ev_id='4'
Now we can `git grep WIFI_EVENT` in ESP-IDF, which learns us that the event is coming from the esp_wifi component, and that the events are defined in `components/esp_wifi/include/esp_wifi_types.h`
In that file, we can find that ev_id 4 is WIFI_EVENT_STA_CONNECTED, which triggers when the station connected to the AP.
This particular event is expected to occur, so we might consider silencing it, or logging it with a human readable message.

network: print ev_base when logging unhandled event

---

main/idf_component.yml
main/was.c

This is the current most recent version of esp_websocket_client.
Torture test results: 1000/1000.

idf: bump esp_websocket_client component to 1.4.0

---

Dockerfile

This is the current most recent version of ESP-IDF 5.2.
Torture test results: 1000/1000.

Dockerfile: bump ESP-IDF to v5.2.5

---

.github/workflows/build-willow.yml

The download-artifact action tries to download all artifacts, but fails if an artifact is not in zip format. At some point something decided to start uploading Docker build summary, which is not in zip format, causing this problem.
[Insert rant about Github Actions here]
https://github.com/actions/toolkit/pull/1874#pullrequestreview-2655200101

CI: fix error in download-artifact action

---

.github/workflows/meta.yml

And use it in the metadata and build-willow steps. This is required for CI to work properly after the move of the repo to the new HeyWillow org.

CI: add GHCR_URL env var

---

.github/workflows/build-container.yml

I don't understand why this is needed, it wasn't in the previous organisation...

CI: grant write to packages in build-container

---

.github/workflows/build-willow.yml

For some fucked up reason CI keeps failing with useless error messages after the repo move to the new organization. The previous commit fixed part of it, and the next failure looks suspiciously like the previous failure, so let's try the next thing to fix it.
Seriously though, Github Actions is a total piece of fucking garbage.

CI: grant read on packages in build-willow

---

.github/workflows/meta.yml

Attempt to fix the following error:
invalid reference format: repository name (HeyWillow/willow) must be lowercase
This is just ridiculous. Seriously, Github Actions is useless.

CI: lowercase GHCR_URL

---

misc/torture.awk

This should be improved, e.g. current ESP-IDF does no longer print min_free_iram nor min_free_spiram, but committing it now so it doesn't get lost.

misc: add parse script for torture logs

---

main/audio.c

When an endpoint takes a long time to respond, the display timer might have already turned of the display when the response arrives. Reset the timer and turn on the display in play_audio so the display is always on when an audio response is played.

audio: turn on display in play_audio

---

main/audio.c
main/config.c
main/endpoint/hass.c
main/http.c

The size arg to calloc should be the second arg. This fixes a bunch of warnings when building with ESP-IDF 5.4 / GCC 14.

treewide: fix calloc args

---

main/endpoint/hass.c

I'm not sure when the original issue started, but at some point my home assistant logs started getting spammed with `Disconnected: Did not receive auth message within 10 seconds` for all three of my willow devices. Restarting home assistant and the willow devices did not resolve the issue. After looking at the home assistant WS handler and how willow communicates with home assistant over WS, my theory is that willow was sending the auth token to home assistant even before it has asked for it. Then when it does ask for the auth token, willow does not respond and the connection eventually times out. 
This PR fixes this issue by having willow send the auth token only after home assistant has asked for it (by checking the `type` property in WS messages). After flashing this change to my …

Home Assistant WS: Send auth token upon auth request

---

main/audio.c
main/audio.h
main/input.c
main/shared.h

Apparently the ESP32-S3-BOX-Lite uses different audio chips than the other ESP32-S3-BOX variants. We unconditionally call es7210_adc_set_gain() to set the MIC gain, and with ESP-ADF 2.7 and ESP-IDF 5.3, using the new I2C driver, this causes a crash due to the es7210 i2c_handle being NULL.
Fix this by using audio_codec_set_volume on the ADC audio handle. Also replace es7210_adc_set_gain in the input key service callback, to have consistent code.
Fixes: #437

Rework unmute and MIC gain handling
